<?php
require_once('C:/wamp64/www/Project/mini - Copy/TCPDF-main/TCPDF-main/tcpdf.php');
include('connection.php');
session_start();

// Fetch all mentor-student pairs from the mentor_student_tab
$fetch_pairs = "SELECT * from `mentor_student_tab`";
$pairs_result = mysqli_query($con, $fetch_pairs);

// Extend TCPDF class to override header and footer
class MYPDF extends TCPDF {
    // Custom header for the first page only
    public function Header() {
        if ($this->page == 1) {
            // Set background color for the header
            $this->SetFillColor(230, 230, 255); // Light blue background
            // Set font for the header
            $this->SetFont('helvetica', 'B', 16);
            // Add "BookBridge" on the top left with a background color
            $this->Cell(0, 15, 'BookBridge', 0, 0, 'L', 1, '', 0, false, 'T', 'M');
            $this->Ln(20); // Add space after the header
        }
    }

    // Custom footer for the last page only
    public function Footer() {
        if ($this->page == $this->getNumPages()) {
            $this->SetY(-15); // Position the footer 15mm from the bottom
            // Set font for the footer
            $this->SetFont('helvetica', 'I', 10);
            $this->SetTextColor(0, 102, 204); // Blue color for footer text
            $this->Cell(0, 10, 'Generated by BookBridge', 0, 0, 'C');
        }
    }
}

// Create new PDF document
$pdf = new MYPDF();
$pdf->SetCreator('Mentor-Student Details');
$pdf->SetTitle('Mentor-Student Details');

// Add the first page with a colorful and bold title
$pdf->AddPage();

// Set font for the content and add a colorful title
$pdf->SetFont('helvetica', 'B', 20);
$pdf->SetTextColor(0, 102, 204); // Blue color for title
$pdf->Cell(0, 20, 'Mentor-Student Combination', 0, 1, 'C');
$pdf->Ln(10); // Add some space after the title

// Set font and background color for the mentor-student details
$pdf->SetFont('helvetica', '', 12);
$pdf->SetFillColor(245, 245, 245); // Light grey background for content

// Loop through mentor-student pairs and add to the PDF
if (mysqli_num_rows($pairs_result) > 0) {
    while ($pair_row = mysqli_fetch_assoc($pairs_result)) {
        // Set background color for mentor and student details (light yellow)
        $pdf->SetFillColor(255, 255, 153); // Light yellow background
        
        // Mentor Name
        $pdf->SetFont('helvetica', 'B', 14);
        $pdf->SetTextColor(0, 153, 51); // Green for mentor names
        $pdf->Cell(0, 10, 'Mentor: ' . htmlspecialchars($pair_row['mentor_name']), 0, 1, '', 1, 'L', true);
        
        // Student Name
        $pdf->SetFont('helvetica', '', 12);
        $pdf->SetTextColor(0, 0, 0); // Black for student names
        $pdf->Cell(0, 10, 'Student: ' . htmlspecialchars($pair_row['student_name']), 0, 1, '', 1, 'L', true);
        
        $pdf->Ln(10); // Add some space after each mentor-student pair
    }
} else {
    // No mentor-student pairs available
    $pdf->SetFont('helvetica', 'I', 12);
    $pdf->SetTextColor(255, 0, 0); // Red for no data message
    $pdf->Cell(0, 10, 'No mentor-student pairs available.', 0, 1, 'C');
}

// Output PDF (force download)
$pdf->Output('mentor_student_details.pdf', 'D');
?>
