<?php
require_once('C:/wamp64/www/Project/mini - Copy/TCPDF-main/TCPDF-main/tcpdf.php');
include('connection.php');
session_start();

// Fetch all book details from the book_details_tab
$fetch_books = "SELECT * FROM book_details_tab ORDER BY book_name ASC";
$books_result = mysqli_query($con, $fetch_books);

// Extend TCPDF class to override header and footer
class MYPDF extends TCPDF {
    // Custom header for the first page only
    public function Header() {
        if ($this->page == 1) {
            // Set background color for the header
            $this->SetFillColor(230, 230, 255); // Light blue background
            // Set font for the header
            $this->SetFont('helvetica', 'B', 16);
            // Add "BookBridge" on the top left with a background color
            $this->Cell(0, 15, 'BookBridge', 0, 0, 'L', 1, '', 0, false, 'T', 'M');
            $this->Ln(20); // Add space after the header
        }
    }

    // Custom footer for the last page only
    public function Footer() {
        if ($this->page == $this->getNumPages()) {
            $this->SetY(-15); // Position the footer 15mm from the bottom
            // Set font for the footer
            $this->SetFont('helvetica', 'I', 10);
            $this->SetTextColor(0, 102, 204); // Blue color for footer text
            $this->Cell(0, 10, 'Generated by BookBridge', 0, 0, 'C');
        }
    }
}

// Create new PDF document
$pdf = new MYPDF();
$pdf->SetCreator('Book Journal');
$pdf->SetTitle('Book Details');

// Add the first page with a colorful and bold title
$pdf->AddPage();

// Set font for the content and add a colorful title
$pdf->SetFont('helvetica', 'B', 20);
$pdf->SetTextColor(0, 102, 204); // Blue color for title
$pdf->Cell(0, 20, 'Book Details', 0, 1, 'C');
$pdf->Ln(10); // Add some space after the title

// Set font and background color for the book details
$pdf->SetFont('helvetica', '', 12);
$pdf->SetFillColor(245, 245, 245); // Light grey background for content

// Loop through book details and add to the PDF
if (mysqli_num_rows($books_result) > 0) {
    while ($book_row = mysqli_fetch_assoc($books_result)) {
        // Book Image
        if (!empty($book_row['book_img'])) {
            $pdf->Image('path_to_book_images/' . htmlspecialchars($book_row['book_img']), '', '', 30, 40, '', '', 'T', false, 300, '', false, false, 1, false, false, false);
        }

        // Set background color for the book name (light yellow)
        $pdf->SetFillColor(255, 255, 153); // Light yellow background
        
        // Book Name
        $pdf->SetFont('helvetica', 'B', 14);
        $pdf->SetTextColor(0, 153, 51); // Green for book names
        $pdf->Cell(0, 10, 'Book: ' . htmlspecialchars($book_row['book_name']), 0, 1, '', 1, 'L', true);

        // Book details
        $pdf->SetFont('helvetica', '', 11);
        $pdf->SetTextColor(0, 0, 0); // Black for content
        $pdf->MultiCell(0, 10, 'Author: ' . htmlspecialchars($book_row['author_name']) . "\n" .
                                'Category: ' . htmlspecialchars($book_row['category']) . "\n" .
                                'Language: ' . htmlspecialchars($book_row['language']) . "\n" .
                                'No. of Copies: ' . htmlspecialchars($book_row['no_of_copies']), 0, 'L', 0, 1);
        
        $pdf->Ln(10); // Add some space after each book
    }
} else {
    // No books available
    $pdf->SetFont('helvetica', 'I', 12);
    $pdf->SetTextColor(255, 0, 0); // Red for no books message
    $pdf->Cell(0, 10, 'No books available.', 0, 1, 'C');
}

// Output PDF (force download)
$pdf->Output('book_details.pdf', 'D');
?>
