<?php
require_once('C:/wamp64/www/Project/mini - Copy/TCPDF-main/TCPDF-main/tcpdf.php');
include('connection.php');
session_start();

// Get the book name, serial number, student name, and mentor name
$book_name = $_GET['bookname'];
$serial_no = $_GET['serialno'];
$studentname = $_SESSION['username'];
$mentor_name = $_SESSION['mentor'];

// Fetch the review for the book from the database
$fetch_reviews = "SELECT review, review_date, pages_cmplted FROM daily_review_tab 
                  WHERE readers_name = '$studentname' AND serial_no = '$serial_no' AND book_name='$book_name' 
                  ORDER BY review_date ASC";
$reviews_result = mysqli_query($con, $fetch_reviews);

// Extend TCPDF class to override header and footer
class MYPDF extends TCPDF {
    protected $studentName;
    protected $mentorName;

    // Set student and mentor names
    public function setHeaderInfo($studentName, $mentorName) {
        $this->studentName = $studentName;
        $this->mentorName = $mentorName;
    }

    // Custom header for the first page only
    public function Header() {
        if ($this->page == 1) {
            // Set background color for the header
            $this->SetFillColor(230, 230, 255); // Light blue background
            // Set font for the header
            $this->SetFont('helvetica', 'B', 16);
            // Add "BookBridge" on the top left with a background color
            $this->Cell(0, 15, 'BookBridge', 0, 0, 'L', 1, '', 0, false, 'T', 'M');
            // Add student name on the top right
            $this->SetFont('helvetica', 'B', 12);
            $this->Cell(0, 15, $this->studentName, 0, 1, 'R', 1, '', 0, false, 'T', 'M');
            // Add mentor name below student name
            $this->SetFont('helvetica', '', 10);
            $this->Cell(0, 10, 'Mentor: ' . $this->mentorName, 0, 0, 'R', 1, '', 0, false, 'T', 'M');
            $this->Ln(20); // Add space after the header
        }
    }

    // Custom footer for the last page only
    public function Footer() {
        if ($this->page == $this->getNumPages()) {
            $this->SetY(-15); // Position the footer 15mm from the bottom
            // Set font for the footer
            $this->SetFont('helvetica', 'I', 10);
            $this->SetTextColor(0, 102, 204); // Blue color for footer text
            $this->Cell(0, 10, 'Generated by BookBridge', 0, 0, 'C');
        }
    }
}

// Create new PDF document
$pdf = new MYPDF();
$pdf->setHeaderInfo($studentname, $mentor_name); // Pass student and mentor names to the PDF header
$pdf->SetCreator('Book Journal');
$pdf->SetTitle('Book Review');

// Add the first page with a colorful and bold title
$pdf->AddPage();

// Set font for the content and add a colorful title
$pdf->SetFont('helvetica', 'B', 20);
$pdf->SetTextColor(0, 102, 204); // Blue color for title
$pdf->Cell(0, 20, 'Daily Book Journal: ' . htmlspecialchars($book_name), 0, 1, 'C');
$pdf->Ln(10); // Add some space after the title

// Set a background for the first page's content area (light grey)
$pdf->SetFillColor(245, 245, 245); // Light grey
$pdf->SetFont('helvetica', '', 12);

// Loop through reviews and add to the PDF
if (mysqli_num_rows($reviews_result) > 0) {
    while ($review_row = mysqli_fetch_assoc($reviews_result)) {
        $pdf->SetFont('helvetica', 'B', 14);
        $pdf->SetTextColor(0, 153, 51); // Green for page numbers
        $pdf->Cell(0, 10, 'Page ' . htmlspecialchars($review_row['pages_cmplted']) . ':', 0, 1, '', 1);
        
        // Set font and text color for the review content
        $pdf->SetFont('helvetica', '', 11);
        $pdf->SetTextColor(0, 0, 0); // Black for review content
        $pdf->MultiCell(0, 10, htmlspecialchars($review_row['review']), 0, 'L', 1, 1);

        // Set font and color for review date
        $pdf->SetFont('helvetica', 'I', 10);
        $pdf->SetTextColor(128, 128, 128); // Grey color for date
        $pdf->Cell(0, 10, 'Uploaded on: ' . htmlspecialchars($review_row['review_date']), 0, 1, '', 1);
        $pdf->Ln(5); // Add some space after each review
    }
} else {
    // No reviews available
    $pdf->SetFont('helvetica', 'I', 12);
    $pdf->SetTextColor(255, 0, 0); // Red for no reviews message
    $pdf->Cell(0, 10, 'No reviews available for this book.', 0, 1, 'C');
}

// Output PDF (force download)
$pdf->Output('review.pdf', 'D');
?>
